import { AzureFunction, Context, HttpRequest } from '@azure/functions';
import { ClientFactory } from '../src/factories/ClientFactory';
import { ClientService } from '../src/application/services/ClientService';
import { FunctionHandler } from '../src/application/services/Main';
import {
  ErrorHandlerMiddleware,
  updateErrorContext,
  ErrorContext,
} from '../src/shared/ErrorHandler';
import { LogModel } from '../src/domain/entities/LogModel';
import { Client } from '../src/domain/entities/Client';

const funcCreateClientImpl = async function (
  context: Context,
  req: HttpRequest,
  log: LogModel,
  errorContext: ErrorContext
): Promise<void> {
  log.logInfo(`🚀 Starting client creation process for URL "${req.url}"`);

  updateErrorContext(errorContext, {
    step: 'validation',
    operation: 'client_creation',
    entityType: 'client',
  });

  if (!req.body) {
    context.res = {
      status: 400,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
      },
      body: JSON.stringify({
        success: false,
        error: 'Bad Request',
        message: 'Request body is required',
      }),
    };
    return;
  }

  updateErrorContext(errorContext, { step: 'service_initialization' });

  const clientService: ClientService = await ClientFactory(log);
  log.logInfo(`✅ ClientService initialized successfully`);

  updateErrorContext(errorContext, { step: 'field_validation' });

  // Validate required fields
  const requiredFields = ['name'];
  const missingFields = requiredFields.filter((field) => !req.body[field]);

  if (missingFields.length > 0) {
    context.res = {
      status: 400,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
      },
      body: JSON.stringify({
        success: false,
        error: 'Bad Request',
        message: `Missing required fields: ${missingFields.join(', ')}`,
      }),
    };
    return;
  }

  updateErrorContext(errorContext, { step: 'client_creation' });

  // Create client data without ID (let database auto-generate it)
  const clientData: Omit<Client, 'id'> = {
    name: req.body.name,
    companyName: req.body.companyName || '',
    companyDocument: req.body.companyDocument || '',
    rut: req.body.rut || '',
    phoneNumber: req.body.phoneNumber || '',
    address: req.body.address || '',
    creationDate: req.body.creationDate || new Date().toISOString(),
    frequentClient: req.body.frequentClient || '',
    created: req.body.created || new Date().toISOString(),
    photoFileName: req.body.photoFileName || undefined,
  };

  updateErrorContext(errorContext, {
    entityData: clientData,
    creationState: { clientCreated: false },
  });

  // Cast to Client type (ID will be generated by database)
  const clientToCreate = { id: '', ...clientData } as Client;

  log.logInfo(`📝 Creating client with name: ${clientData.name}`);
  const createdClient = await clientService.createClient(clientToCreate);

  updateErrorContext(errorContext, {
    creationState: { clientCreated: true },
  });

  log.logInfo(`✅ Successfully created client with ID: ${createdClient.id}`);

  context.res = {
    status: 201,
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    },
    body: JSON.stringify({
      success: true,
      data: createdClient,
      message: 'Client created successfully',
    }),
  };
};

// Apply both middlewares: first authentication, then error handling
const funcCreateClient: AzureFunction = FunctionHandler(
  ErrorHandlerMiddleware(funcCreateClientImpl)
);

export = funcCreateClient;
